menu:
  Home: /
  Archives: archives
  page:
    About: about

widgets:
- tag

excerpt_link: Continue →

mathjax: true
fancybox: true
print: true

social:
  twitter: true
  github: true
  gplus: true
  rss: true
  linkedin: true
  facebook: true
  coderwall: true
  pinterest: true

twitter:
  username:

github:
  username:

gplus:
  username:

linkedin:
  username:

facebook:
  username:

coderwall:
  username:

pinterest:
  username:

addit:
  facebook: false
  twitter: true
  gplus: true
  pinit: false
  publid: