menu:
  Home: /
  Archives: archives
  page:
    About: about

excerpt_link: Continue →

mathjax: true
fancybox: true

social:
  twitter: true
  github: true
  rss: true

twitter:
  username: nuklly

github:
  username: nuklly

addit:
  facebook: false
  twitter: true
  gplus: true
  pinit: false
  publid: ra-5206464767bea141